"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, ChevronLeft, ChevronRight, Heart, Menu, Sparkles, X } from "lucide-react";
import { getSupabaseClient } from "@/lib/supabase";

type Chapter={id:string;chapter_number:number;chapter_label:string;title:string;excerpt:string;content:string;mood:string};
type Story={id:string;title:string;subtitle:string;author:string};
type Stats={views:number;favorites:number;chapters:number};

export default function Home(){
 const [story,setStory]=useState<Story|null>(null),[chapters,setChapters]=useState<Chapter[]>([]),[active,setActive]=useState(0),[loading,setLoading]=useState(true),[menuOpen,setMenuOpen]=useState(false),[loadError,setLoadError]=useState<string|null>(null),[stats,setStats]=useState<Stats>({views:0,favorites:0,chapters:0}),[favorite,setFavorite]=useState(false);
 useEffect(()=>{let cancelled=false;async function load(){try{const supabase=getSupabaseClient();const {data:s,error:se}=await supabase.from("novel_stories").select("id,title,subtitle,author").eq("slug","perjalanan-rizki-habibi").eq("status","published").single();if(se)throw se;if(!s)throw new Error("Cerita tidak ditemukan.");const {data:c,error:ce}=await supabase.from("novel_chapters").select("id,chapter_number,chapter_label,title,excerpt,content,mood").eq("story_id",s.id).eq("published",true).order("sort_order",{ascending:true});if(ce)throw ce;if(!c?.length)throw new Error("Belum ada chapter yang diterbitkan.");if(!cancelled){setStory(s);setChapters(c);setLoading(false)}}catch(e){if(!cancelled){setLoadError(e instanceof Error?e.message:"Cerita gagal dimuat.");setLoading(false)}}}load();return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!story)return;const supabase=getSupabaseClient();let key=localStorage.getItem("novelmu-visitor");if(!key){key=crypto.randomUUID();localStorage.setItem("novelmu-visitor",key)}setFavorite(localStorage.getItem("novelmu-favorite")==="1");(async()=>{if(localStorage.getItem("novelmu-viewed")!=="1"){await supabase.functions.invoke("novelmu-api",{body:{action:"engage",story_id:story.id,event_type:"view",visitor_key:key}});localStorage.setItem("novelmu-viewed","1")}const {data,error}=await supabase.functions.invoke("novelmu-api",{body:{action:"stats",story_id:story.id}});if(!error&&data)setStats(data)})()},[story]);
 const chapter=chapters[active],progress=chapters.length?((active+1)/chapters.length)*100:0;
 const moodText=useMemo(()=>{if(!chapter)return "";const map:Record<string,string>={romantis:"sebuah bab tentang rasa yang tumbuh perlahan",sendu:"sebuah bab tentang jalan yang pernah terasa berat",reflektif:"sebuah bab untuk menatap kembali perjalanan",nostalgia:"sebuah bab yang mengingatkan rumah dan masa lalu",harapan:"sebuah bab tentang hari yang belum datang"};return map[chapter.mood]??"sebuah bab dari perjalanan yang terus berjalan"},[chapter]);
 const toggleFavorite=async()=>{if(!story||favorite)return;const key=localStorage.getItem("novelmu-visitor")||crypto.randomUUID();localStorage.setItem("novelmu-visitor",key);const {error}=await getSupabaseClient().functions.invoke("novelmu-api",{body:{action:"engage",story_id:story.id,event_type:"favorite",visitor_key:key}});if(!error){setFavorite(true);localStorage.setItem("novelmu-favorite","1");setStats(s=>({...s,favorites:s.favorites+1}))}};
 const go=(d:number)=>{setActive(c=>Math.min(Math.max(c+d,0),chapters.length-1));window.scrollTo({top:0,behavior:"smooth"})};
 if(loading)return <main className="loading"><div className="loading-book"><div className="loading-book-page"/><div className="loading-book-page page-two"/><Heart className="loading-book-heart" size={24} fill="currentColor"/></div><div className="loading-brand">NOVELMU</div><p>Menyiapkan halaman cerita...</p><div className="loading-dots"><i/><i/><i/></div></main>;
 if(loadError||!story||!chapter)return <main className="loading error-state"><div className="error-icon"><BookOpen size={36}/></div><p>{loadError??"Cerita belum tersedia."}</p><small>Periksa konfigurasi Supabase dan deployment Vercel.</small></main>;
 const paragraphs=chapter.content.split(/\n\s*\n/).map(t=>t.trim()).filter(Boolean);
 return <main className="novel-shell"><div className="grain"/>
  <header className="topbar"><button className="icon-btn mobile-only" onClick={()=>setMenuOpen(true)} aria-label="Buka daftar bab"><Menu size={21}/></button><a className="brand" href="#top">NOVELMU</a><div className="topbar-meta">Rizki Habibi · Kisah Nyata</div><div className="topbar-right"><span>{active+1} / {chapters.length}</span><div className="progress"><span style={{width:progress+"%"}}/></div></div></header>
  <aside className={menuOpen?"chapter-drawer open":"chapter-drawer"} aria-hidden={!menuOpen}><div className="drawer-head"><div><small>DAFTAR BAB</small><strong>Perjalanan</strong></div><button className="icon-btn" onClick={()=>setMenuOpen(false)} aria-label="Tutup daftar bab"><X size={20}/></button></div><div className="chapter-list">{chapters.map((item,index)=><button key={item.id} className={index===active?"chapter-link active":"chapter-link"} onClick={()=>{setActive(index);setMenuOpen(false);window.scrollTo({top:0,behavior:"smooth"})}}><span>{String(item.chapter_number).padStart(2,"0")}</span><div><small>{item.chapter_label}</small><b>{item.title}</b></div></button>)}</div></aside>
  <section id="top" className="hero"><div className="hero-glow"/><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-inner"><p className="eyebrow"><Sparkles size={14}/> SEBUAH NOVEL DIGITAL</p><h1>{story.title}</h1><p className="hero-subtitle">{story.subtitle}</p><div className="author-line"><span className="line"/><span>ditulis oleh {story.author}</span><span className="line"/></div><div className="heart-seal"><Heart size={18} fill="currentColor"/></div><a className="start-reading" href="#reading">Mulai Membaca <ChevronRight size={16}/></a></div></section>
  <section className="stats-strip"><div><strong>{chapters.length}</strong><span>Bab</span></div><div><strong>{stats.views}</strong><span>Pembaca</span></div><div><strong>{stats.favorites}</strong><span>Peminat</span></div><button className={favorite?"favorite-btn active":"favorite-btn"} onClick={toggleFavorite} disabled={favorite}><Heart size={17} fill={favorite?"currentColor":"none"}/>{favorite?"Sudah Menjadi Peminat":"Jadi Peminat"}</button></section>
  <section id="reading" className="reading-layout"><nav className="desktop-chapters"><p>ISI CERITA</p>{chapters.map((item,index)=><button key={item.id} className={index===active?"side-link active":"side-link"} onClick={()=>{setActive(index);window.scrollTo({top:0,behavior:"smooth"})}}><span>{String(item.chapter_number).padStart(2,"0")}</span><em>{item.title}</em></button>)}</nav>
   <article className="chapter-card"><div className="chapter-top"><span>{chapter.chapter_label}</span><span className="chapter-number">BAB {String(chapter.chapter_number).padStart(2,"0")}</span></div><p className="chapter-mood">{moodText}</p><h2>{chapter.title}</h2><p className="excerpt">{chapter.excerpt}</p><div className="ornament"><span/><Heart size={15} fill="currentColor"/><span/></div><div className="story-copy">{paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><div className="chapter-footer"><span>Rizki Habibi</span><span>♥</span></div><div className="reader-nav"><button disabled={active===0} onClick={()=>go(-1)}><ChevronLeft size={18}/> Sebelumnya</button><span className="reader-position">Bab {active+1} dari {chapters.length}</span><button disabled={active===chapters.length-1} onClick={()=>go(1)}>Berikutnya <ChevronRight size={18}/></button></div></article>
  </section><footer className="footer"><Heart size={16} fill="currentColor"/><span>Cerita ini masih berjalan. Halaman terakhir belum ditulis.</span><a href="/admin">Kelola Novel</a><Heart size={16} fill="currentColor"/></footer>
 </main>;
}